### ISSUE TITLE
Allow usage of config file

### ISSUE THREAD

**Issue by smyth64** [francescou/docker-compose-ui#19]
Hi folks,
I really like your project.
Unfortunately I cannot use it in production because I use a config file on my host before using docker-compose up.

It looks like this.

```
  environment: 
    HTML_ROOT: ${HTML_ROOT}

    SITE_TITLE: ${SITE_TITLE}
    ADMIN_USER: ${ADMIN_USER}
    ADMIN_PW: ${ADMIN_PW}
    ADMIN_EMAIL: ${ADMIN_EMAIL}
```

My Startup Script looks like this

```
source config.cf
docker-compose up
```

The advantage is, that I only have to use one config file for everything instead of hardcoding the environment variables inside the docker-compose.yml.

Also my 2. Question. Is it possible to use a custom docker-compose.yml? So I could make a docker-production.yml and so on.

Best Regards
Michael

**Comment by francescou** [comment]
Hi Michael
1. I'm not sure if it can help you, but I've been using the [extends](https://docs.docker.com/compose/extends/#extending-services) keyword to do that, e.g.
   
   **conf.yml**
   
   ``` yml
   
   env:
     environment:
     - FOO=quux
   ```
   
   **docker-compose.yml**
   
   ``` yml
   hello:
     extends:
       file: conf.yml
       service: env
     build: app
     command : #do something with $FOO
   ```
2. it's not (yet) possible since the application is relying on the docker compose [SUPPORTED_FILENAMES](https://github.com/docker/compose/blob/42f4d814d7dd6ad4799ad71ddc738ada954143f6/compose/config/config.py#L103)

thank you

Francesco
