### ISSUE TITLE
Decompose the Compose files

### ISSUE THREAD

**Issue by allamand** [francescou/docker-compose-ui#69]
Hello,

Is it possible for compose-ui instead of reading docker-compose.yml file, to read docker-compose*.yml files ?

I used to specify several docker-compose-files with -f when using docker-compose, that allow me to simplify big docker-compose file maintenability ex : 

```
  -rw-r--r-- 1 cloud docker 3211 Jul 11 09:13 docker-compose-base.yml
  -rw-r--r-- 1 cloud docker  684 Jul  5 10:22 docker-compose-logs.yml
  -rw-r--r-- 1 cloud docker  629 Aug 10 08:44 docker-compose-networks.yml
  -rw-r--r-- 1 cloud docker  771 Jul 11 09:12 docker-compose-traefik.yml
  -rw-r--r-- 1 cloud docker  377 Jul 11 09:18 docker-compose-volumes.yml
```

**Comment by francescou** [comment]
Hi, only _docker-compose.yml_ projects are supported, at the moment.

I will investigate about the technical feasibility of this

**Comment by mmacai** [comment]
@allamand If you want to use something like `docker-compose -f docker-compose.yml -f docker-compose.a.yml up` you can create `.env` file in directory with those files and put there:
`COMPOSE_FILE=docker-compose.yml:docker-compose.a.yml`. You should be able to use multiple compose files, but one should be named `docker-compose.yml`.

**Comment by edyan** [comment]
+1 I have created a tool that "recompose" the docker command line via a config file (https://github.com/edyan/stakkr : it reads a list of services to start and get the right yml files). That's completely dynamic and I can't use your UI (unfortunately!).

My config files are there : https://github.com/edyan/stakkr/tree/master/stakkr/static/services + I use a lot of env variables ...

As docker compose has no api and it's a pure cli tool, maybe it's impossible to "guess" what has been loaded ? 

Thanks !


Edit : I found a way to write the full config dumped from `docker-compose config` and to mount it in a directory that I set as the working dir ... but that does not work ... i have a GUI with no containers. My config is the following (am I missing something?):

```yaml
networks:
  stakkr:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.102.0/24
services:
  apache:
    container_name: mydev_apache
    environment:
      APACHE_GID: '1000'
      APACHE_UID: '1000'
    hostname: mydev_apache
    image: edyan/apache:2.2
    links:
    - php
    mem_limit: 512M
    networks:
      stakkr: null
    volumes:
    - /projects/mydev/home/www-data:/home/www-data:rw
    - /projects/mydev/logs/apache:/var/log/apache2:rw
    - /projects/mydev/www:/var/www:rw
  compose-ui:
    container_name: mydev_ui
    hostname: mydev_ui
    image: francescou/docker-compose-ui
    networks:
      stakkr: null
    volumes:
    - /tmp/stakkr/mydev:/compose-files/stakkr:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    working_dir: /compose-files
  elasticsearch:
    container_name: mydev_elasticsearch
    hostname: mydev_elasticsearch
    image: elasticsearch:1.6
    mem_limit: 512M
    networks:
      stakkr: null
    volumes:
    - /projects/mydev/data/elasticsearch:/usr/share/elasticsearch/data:rw
  maildev:
    container_name: mydev_maildev
    hostname: mydev_maildev
    image: djfarrelly/maildev
    networks:
      stakkr: null
  mysql:
    container_name: mydev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    hostname: mydev_mysql
    image: mysql:5.5
    mem_limit: 1024M
    networks:
      stakkr: null
    volumes:
    - /projects/mydev/conf/mysql-override:/etc/mysql/conf.d:rw
    - /projects/mydev/data/mysql:/var/lib/mysql:rw
  php:
    cap_add:
    - NET_ADMIN
    - NET_RAW
    container_name: mydev_php
    environment:
      ENVIRONMENT: dev
      FPM_GID: '1000'
      FPM_UID: '1000'
    hostname: mydev_php
    image: edyan/php:5.6-git
    mem_limit: 512M
    networks:
      stakkr: null
    volumes:
    - /projects/mydev/conf/php-fpm-override:/etc/php/7.0/fpm/user-conf.d:rw
    - /projects/mydev/conf/php-fpm-override:/etc/php/7.1/fpm/user-conf.d:rw
    - /projects/mydev/conf/php-fpm-override:/etc/php/7.2/fpm/user-conf.d:rw
    - /projects/mydev/conf/php-fpm-override:/etc/php5/fpm/user-conf.d:rw
    - /projects/mydev/home/www-data:/home/www-data:rw
    - /projects/mydev/logs/php:/var/log/php:rw
    - /projects/mydev/www:/var/www:rw
  phpmyadmin:
    container_name: mydev_phpmyadmin
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PMA_HOSTS: mysql
      PMA_PASSWORD: changeme
      PMA_USER: root
    hostname: mydev_phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      stakkr: null
version: '2.2'
```
